# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: cbassuarez.nus
PackageVersion: 0.0.2-preview.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: nus-0.0.2-preview.1-windows-x86_64\bin\nus.exe
    PortableCommandAlias: nus
Commands:
  - nus
ReleaseDate: 2026-09-26
ReleaseNotesUrl: https://github.com/cbassuarez/nus/releases/tag/v0.0.2-preview.1
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cbassuarez/nus/releases/download/v0.0.2-preview.1/nus-0.0.2-preview.1-windows-x86_64.zip
    InstallerSha256: 1CB82F7F8B5C8049DF9F5A7E10A2F2ACEFBC18D5733B58881A28733BA0695C56
ManifestType: installer
ManifestVersion: 1.6.0
