import {SITE,icon} from '../layout.mjs';
export default {title:'Around nus',path:'/panels/',depth:1,
 description:'A look around the nus workspace: your shell beside a page, a command history you can navigate, Hatch, and a home you can make your own.',
 module:"import { mountFilms } from '../assets/js/films.js'; mountFilms();",
 body:`<section class="section"><div class="section__in"><p class="cap">A look around</p><h1>One project.<br><em>A few good neighbours.</em></h1><p class="lede">Shells and pages share the window. Your work gets a place to stay.</p><nav class="feature-index" aria-label="Workspace features"><a href="#workspace">The workspace</a><a href="#history">History</a><a href="#hatch">Hatch</a><a href="#home">Your home</a></nav></div></section>
<section class="section" id="workspace"><div class="section__in"><div class="sectionhead"><h2>Your shell, with a view.</h2><span class="cap">01 / workspace</span></div><p>Run a build, check its output, and open the page beside it. Tabs, splits, and named spaces give each project its own arrangement.</p><figure class="product-shot"><img src="../assets/films/workspace.png" width="1600" height="1000" loading="lazy" alt="nus on a Mac: the site build in a shell beside this site’s download page."><figcaption>This site, built and opened inside nus.</figcaption></figure><div class="feature-pair"><p><strong>Bring the tools you use.</strong><br>Your shell configuration and command-line tools work in a real terminal. Pages use Chromium, with their own navigation and developer tools.</p><p><strong>Keep a useful arrangement.</strong><br>Put a server beside its preview, keep documentation near a shell, or give an assistant a terminal of its own.</p></div></div></section>
<section class="section" id="history"><div class="section__in"><div class="sectionhead"><h2>Find your way back.</h2><span class="cap">02 / history</span></div><p>Command history comes first. A scrollable map gives the session a shape; select a command to inspect its output. Play through a recording when sequence and timing matter.</p><figure class="app-film" data-film><div class="app-film__bar"><span>Command history</span><span>Recorded from the app</span></div><video width="1600" height="1000" poster="../assets/films/history.png" preload="none" muted playsinline loop aria-label="Navigating command history and recorded output in nus." data-src="../assets/films/history.mp4"></video><div class="app-film__caption"><figcaption>A map of what happened.<span>The Mac build, from a scripted take. Paced for reading.</span></figcaption><button class="film-toggle" data-film-toggle>Play recording ↗</button></div><p class="film-error small" data-film-error hidden>The recording didn’t load. The still is a frame from the same take.</p></figure></div></section>
<section class="section" id="hatch"><div class="section__in personal-grid"><div><p class="cap">03 / Hatch</p><h2>Your workspace,<br><em>one shortcut away.</em></h2></div><div><p>Summon a shell without searching for your main window. Hatch keeps named sessions close and lets ongoing work report when it finishes or needs input.</p><p>Choose a dropdown from the top edge or a centred panel. Move the same session into the full workspace when you need more room.</p><p class="small dim">Window placement, focus restoration, and status access vary by platform and desktop. These are part of ongoing native-platform testing.</p></div></div></section>
<section class="section" id="home"><div class="section__in"><div class="sectionhead"><h2>A place to begin.</h2><span class="cap">04 / your home</span></div><p>Start with a prompt. Choose shell suggestions, web destinations, assistant routing, or a mix. Presets get you going; individual controls let you make your own arrangement.</p><figure class="product-shot"><img src="../assets/films/home.png" width="1600" height="1000" loading="lazy" alt="The nus home prompt with its Memphis background and configurable suggestions."><figcaption>Type, colours, backgrounds, and suggestions belong to you.</figcaption></figure><div class="feature-pair"><p><strong>Your assistant, in your workspace.</strong><br>Configure Claude, Codex, and Ollama, inspect how they are launched, and send work to a shell you can return to. Provider tools need to be installed and authenticated separately.</p><p><strong>Small choices add up.</strong><br>Pick a typeface you like reading. Keep the backdrop quiet, or put something playful behind the prompt. Adjust the details without replacing your workflow.</p></div><div class="row"><a class="btn btn--signal" href="../download/">${icon('download-simple')}Get nus</a><a href="${SITE.repo}/issues">Tell us what needs work ↗</a></div></div></section>`};
