# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: cbassuarez.nus
PackageVersion: 0.0.1-preview.9
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: nus-0.0.1-preview.9-windows-x86_64\bin\nus.exe
    PortableCommandAlias: nus
Commands:
  - nus
ReleaseDate: 2026-09-24
ReleaseNotesUrl: https://github.com/cbassuarez/nus/releases/tag/v0.0.1-preview.9
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cbassuarez/nus/releases/download/v0.0.1-preview.9/nus-0.0.1-preview.9-windows-x86_64.zip
    InstallerSha256: 6568E1A8726FBA9CF6331EF882296CACF461A99F6CD03779A9DBFEB8AAC6D1A5
ManifestType: installer
ManifestVersion: 1.6.0
