# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: cbassuarez.nus
PackageVersion: 0.0.1-preview.8
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: nus-0.0.1-preview.8-windows-x86_64\bin\nus.exe
    PortableCommandAlias: nus
Commands:
  - nus
ReleaseDate: 2026-09-23
ReleaseNotesUrl: https://github.com/cbassuarez/nus/releases/tag/v0.0.1-preview.8
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cbassuarez/nus/releases/download/v0.0.1-preview.8/nus-0.0.1-preview.8-windows-x86_64.zip
    InstallerSha256: 619739BAAD9D330BE1F42F57E720DF46A138A8529C70E98A16E9A00DE9240739
ManifestType: installer
ManifestVersion: 1.6.0
